stages:
  - compilation

wishlist_build:
  stage: compilation
  script:
    - pwd
    - source /home/latomefw/wishlist/venv/bin/activate
    - python python/wishlist.py
  tags:
    - wishlist
  artifacts:
    paths:
      - firmware
      - software