-- Automatically generated by WhishList - https://github.com/mvsoliveira/wishlist/
-- Package name: example_pkg
-- Description : IPbus address table for the L1Calo gFEX zynq FPGA

library ieee;
use ieee.std_logic_1164.all;
library work;
use work.example_pkg.all;

entity example_address_decoder is
port(
    clk_i : in std_logic;
    read_i : in std_logic;
    write_i : in std_logic;
    address_i : in std_logic_vector(31 downto 0);
    data_i : in std_logic_vector(31 downto 0);
    data_o : out std_logic_vector(31 downto 0);
    example_status_i : in example_status_record_type;
    example_control_o : out example_control_record_type

);
end entity example_address_decoder;


architecture rtl of example_address_decoder is

signal int_example_control : example_control_record_type;
signal int_example_status : example_status_record_type;

begin

example_control_o <= int_example_control;
int_example_status <= example_status_i;

address_decoder_p : process (clk_i) is
begin
    if rising_edge(clk_i) then
        if (read_i = '1') then
            case address_i is
                when X"A0010000" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(0).tap(0)(27 downto 0);
                when X"A0010004" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(0).tap(1)(27 downto 0);
                when X"A0010008" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(0).tap(2)(27 downto 0);
                when X"A001000C" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(0).tap(3)(27 downto 0);
                when X"A0010010" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(1).tap(0)(27 downto 0);
                when X"A0010014" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(1).tap(1)(27 downto 0);
                when X"A0010018" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(1).tap(2)(27 downto 0);
                when X"A001001C" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(1).tap(3)(27 downto 0);
                when X"A0010020" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(2).tap(0)(27 downto 0);
                when X"A0010024" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(2).tap(1)(27 downto 0);
                when X"A0010028" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(2).tap(2)(27 downto 0);
                when X"A001002C" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(2).tap(3)(27 downto 0);
                when X"A0010030" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(3).tap(0)(27 downto 0);
                when X"A0010034" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(3).tap(1)(27 downto 0);
                when X"A0010038" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(3).tap(2)(27 downto 0);
                when X"A001003C" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(3).tap(3)(27 downto 0);
                when X"A0010040" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(4).tap(0)(27 downto 0);
                when X"A0010044" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(4).tap(1)(27 downto 0);
                when X"A0010048" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(4).tap(2)(27 downto 0);
                when X"A001004C" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(4).tap(3)(27 downto 0);
                when X"A0010050" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(5).tap(0)(27 downto 0);
                when X"A0010054" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(5).tap(1)(27 downto 0);
                when X"A0010058" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(5).tap(2)(27 downto 0);
                when X"A001005C" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(0).fir.sc(5).tap(3)(27 downto 0);
                when X"A0010060" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(0).tap(0)(27 downto 0);
                when X"A0010064" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(0).tap(1)(27 downto 0);
                when X"A0010068" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(0).tap(2)(27 downto 0);
                when X"A001006C" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(0).tap(3)(27 downto 0);
                when X"A0010070" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(1).tap(0)(27 downto 0);
                when X"A0010074" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(1).tap(1)(27 downto 0);
                when X"A0010078" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(1).tap(2)(27 downto 0);
                when X"A001007C" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(1).tap(3)(27 downto 0);
                when X"A0010080" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(2).tap(0)(27 downto 0);
                when X"A0010084" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(2).tap(1)(27 downto 0);
                when X"A0010088" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(2).tap(2)(27 downto 0);
                when X"A001008C" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(2).tap(3)(27 downto 0);
                when X"A0010090" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(3).tap(0)(27 downto 0);
                when X"A0010094" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(3).tap(1)(27 downto 0);
                when X"A0010098" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(3).tap(2)(27 downto 0);
                when X"A001009C" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(3).tap(3)(27 downto 0);
                when X"A00100A0" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(4).tap(0)(27 downto 0);
                when X"A00100A4" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(4).tap(1)(27 downto 0);
                when X"A00100A8" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(4).tap(2)(27 downto 0);
                when X"A00100AC" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(4).tap(3)(27 downto 0);
                when X"A00100B0" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(5).tap(0)(27 downto 0);
                when X"A00100B4" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(5).tap(1)(27 downto 0);
                when X"A00100B8" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(5).tap(2)(27 downto 0);
                when X"A00100BC" =>
                    data_o(31 downto 4) <= int_example_control.user_code.pu(1).fir.sc(5).tap(3)(27 downto 0);
                    data_o(3) <= int_example_status.pll_lock;
                when others => null;
            end case;
        end if;
        if (write_i = '1') then
            case address_i is
                when X"A0010000" =>
                    int_example_control.user_code.pu(0).fir.sc(0).tap(0)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010004" =>
                    int_example_control.user_code.pu(0).fir.sc(0).tap(1)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010008" =>
                    int_example_control.user_code.pu(0).fir.sc(0).tap(2)(27 downto 0) <= data_i(31 downto 4);
                when X"A001000C" =>
                    int_example_control.user_code.pu(0).fir.sc(0).tap(3)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010010" =>
                    int_example_control.user_code.pu(0).fir.sc(1).tap(0)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010014" =>
                    int_example_control.user_code.pu(0).fir.sc(1).tap(1)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010018" =>
                    int_example_control.user_code.pu(0).fir.sc(1).tap(2)(27 downto 0) <= data_i(31 downto 4);
                when X"A001001C" =>
                    int_example_control.user_code.pu(0).fir.sc(1).tap(3)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010020" =>
                    int_example_control.user_code.pu(0).fir.sc(2).tap(0)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010024" =>
                    int_example_control.user_code.pu(0).fir.sc(2).tap(1)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010028" =>
                    int_example_control.user_code.pu(0).fir.sc(2).tap(2)(27 downto 0) <= data_i(31 downto 4);
                when X"A001002C" =>
                    int_example_control.user_code.pu(0).fir.sc(2).tap(3)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010030" =>
                    int_example_control.user_code.pu(0).fir.sc(3).tap(0)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010034" =>
                    int_example_control.user_code.pu(0).fir.sc(3).tap(1)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010038" =>
                    int_example_control.user_code.pu(0).fir.sc(3).tap(2)(27 downto 0) <= data_i(31 downto 4);
                when X"A001003C" =>
                    int_example_control.user_code.pu(0).fir.sc(3).tap(3)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010040" =>
                    int_example_control.user_code.pu(0).fir.sc(4).tap(0)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010044" =>
                    int_example_control.user_code.pu(0).fir.sc(4).tap(1)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010048" =>
                    int_example_control.user_code.pu(0).fir.sc(4).tap(2)(27 downto 0) <= data_i(31 downto 4);
                when X"A001004C" =>
                    int_example_control.user_code.pu(0).fir.sc(4).tap(3)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010050" =>
                    int_example_control.user_code.pu(0).fir.sc(5).tap(0)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010054" =>
                    int_example_control.user_code.pu(0).fir.sc(5).tap(1)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010058" =>
                    int_example_control.user_code.pu(0).fir.sc(5).tap(2)(27 downto 0) <= data_i(31 downto 4);
                when X"A001005C" =>
                    int_example_control.user_code.pu(0).fir.sc(5).tap(3)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010060" =>
                    int_example_control.user_code.pu(1).fir.sc(0).tap(0)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010064" =>
                    int_example_control.user_code.pu(1).fir.sc(0).tap(1)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010068" =>
                    int_example_control.user_code.pu(1).fir.sc(0).tap(2)(27 downto 0) <= data_i(31 downto 4);
                when X"A001006C" =>
                    int_example_control.user_code.pu(1).fir.sc(0).tap(3)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010070" =>
                    int_example_control.user_code.pu(1).fir.sc(1).tap(0)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010074" =>
                    int_example_control.user_code.pu(1).fir.sc(1).tap(1)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010078" =>
                    int_example_control.user_code.pu(1).fir.sc(1).tap(2)(27 downto 0) <= data_i(31 downto 4);
                when X"A001007C" =>
                    int_example_control.user_code.pu(1).fir.sc(1).tap(3)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010080" =>
                    int_example_control.user_code.pu(1).fir.sc(2).tap(0)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010084" =>
                    int_example_control.user_code.pu(1).fir.sc(2).tap(1)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010088" =>
                    int_example_control.user_code.pu(1).fir.sc(2).tap(2)(27 downto 0) <= data_i(31 downto 4);
                when X"A001008C" =>
                    int_example_control.user_code.pu(1).fir.sc(2).tap(3)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010090" =>
                    int_example_control.user_code.pu(1).fir.sc(3).tap(0)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010094" =>
                    int_example_control.user_code.pu(1).fir.sc(3).tap(1)(27 downto 0) <= data_i(31 downto 4);
                when X"A0010098" =>
                    int_example_control.user_code.pu(1).fir.sc(3).tap(2)(27 downto 0) <= data_i(31 downto 4);
                when X"A001009C" =>
                    int_example_control.user_code.pu(1).fir.sc(3).tap(3)(27 downto 0) <= data_i(31 downto 4);
                when X"A00100A0" =>
                    int_example_control.user_code.pu(1).fir.sc(4).tap(0)(27 downto 0) <= data_i(31 downto 4);
                when X"A00100A4" =>
                    int_example_control.user_code.pu(1).fir.sc(4).tap(1)(27 downto 0) <= data_i(31 downto 4);
                when X"A00100A8" =>
                    int_example_control.user_code.pu(1).fir.sc(4).tap(2)(27 downto 0) <= data_i(31 downto 4);
                when X"A00100AC" =>
                    int_example_control.user_code.pu(1).fir.sc(4).tap(3)(27 downto 0) <= data_i(31 downto 4);
                when X"A00100B0" =>
                    int_example_control.user_code.pu(1).fir.sc(5).tap(0)(27 downto 0) <= data_i(31 downto 4);
                when X"A00100B4" =>
                    int_example_control.user_code.pu(1).fir.sc(5).tap(1)(27 downto 0) <= data_i(31 downto 4);
                when X"A00100B8" =>
                    int_example_control.user_code.pu(1).fir.sc(5).tap(2)(27 downto 0) <= data_i(31 downto 4);
                when X"A00100BC" =>
                    int_example_control.user_code.pu(1).fir.sc(5).tap(3)(27 downto 0) <= data_i(31 downto 4);
                when others => null;
            end case;
        end if;
    end if;
end process address_decoder_p;

end architecture rtl;