-- Automatically generated by WhishList - https://github.com/mvsoliveira/wishlist/
-- Package name: l1calogfex_pkg
-- Description : IPbus address table for the L1Calo gFEX zynq FPGA

library ieee;
use ieee.std_logic_1164.all;

package l1calogfex_pkg is

-- register data types

subtype l1calogfex_ctest_reg_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_n_bcrd_ctrl_glbl_lnks_subtype is std_logic_vector(8 downto 0);
subtype l1calogfex_n_bcrd_ctrl_jet_lnks_subtype is std_logic_vector(8 downto 0);
subtype l1calogfex_n_bcrd_ctrl_twr_lnks_subtype is std_logic_vector(10 downto 0);
subtype l1calogfex_n_bcrd_ctrl_twr_lnks_read_subtype is std_logic;
subtype l1calogfex_gbt_ctrl_sync_subtype is std_logic;
subtype l1calogfex_gbt_ctrl_rst_subtype is std_logic;
subtype l1calogfex_ecr_ctrl_value_subtype is std_logic_vector(7 downto 0);
subtype l1calogfex_ecr_ctrl_clear_subtype is std_logic;
subtype l1calogfex_ecr_ctrl_update_subtype is std_logic;
subtype l1calogfex_date_time_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_git_hash_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_fw_ver_code_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_aipb_tx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_aipb_tx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_bipb_tx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_bipb_tx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_cipb_tx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_cipb_tx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_aipb_rx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_bipb_rx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_cipb_rx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_zipb_tx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_zipb_tx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_zipb_rx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_aipb_tx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_bipb_tx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_cipb_tx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_aipb_rx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_aipb_rx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_bipb_rx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_bipb_rx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_cipb_rx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_cipb_rx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_zipb_tx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_zipb_rx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_zipb_rx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_init_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_test_init_stat_r_subtype is std_logic_vector(49 downto 0);
subtype l1calogfex_test_init_stat_rw_subtype is std_logic_vector(39 downto 0);

-- status hierarchy data types
    
type l1calogfex_status_n_bcrd_ctrl_record_type is record
    GLBL_LNKS : l1calogfex_n_bcrd_ctrl_glbl_lnks_subtype;
    JET_LNKS : l1calogfex_n_bcrd_ctrl_jet_lnks_subtype;
    TWR_LNKS : l1calogfex_n_bcrd_ctrl_twr_lnks_subtype;
    TWR_LNKS_read : l1calogfex_n_bcrd_ctrl_twr_lnks_read_subtype;
end record l1calogfex_status_n_bcrd_ctrl_record_type;
    
type l1calogfex_status_gbt_ctrl_record_type is record
    SYNC : l1calogfex_gbt_ctrl_sync_subtype;
    RST : l1calogfex_gbt_ctrl_rst_subtype;
end record l1calogfex_status_gbt_ctrl_record_type;
    
type l1calogfex_status_ecr_ctrl_record_type is record
    VALUE : l1calogfex_ecr_ctrl_value_subtype;
    CLEAR : l1calogfex_ecr_ctrl_clear_subtype;
    UPDATE : l1calogfex_ecr_ctrl_update_subtype;
end record l1calogfex_status_ecr_ctrl_record_type;
    
type l1calogfex_status_test_record_type is record
    INIT_STAT_r : l1calogfex_test_init_stat_r_subtype;
    INIT_STAT_rw : l1calogfex_test_init_stat_rw_subtype;
end record l1calogfex_status_test_record_type;
    
type l1calogfex_status_record_type is record
    CTEST_REG : l1calogfex_ctest_reg_subtype;
    N_BCRD_CTRL : l1calogfex_status_n_bcrd_ctrl_record_type;
    GBT_CTRL : l1calogfex_status_gbt_ctrl_record_type;
    ECR_CTRL : l1calogfex_status_ecr_ctrl_record_type;
    DATE_TIME : l1calogfex_date_time_subtype;
    GIT_HASH : l1calogfex_git_hash_subtype;
    FW_VER_CODE : l1calogfex_fw_ver_code_subtype;
    AIPB_TX_CTRL : l1calogfex_aipb_tx_ctrl_subtype;
    AIPB_TX_DATA : l1calogfex_aipb_tx_data_subtype;
    BIPB_TX_CTRL : l1calogfex_bipb_tx_ctrl_subtype;
    BIPB_TX_DATA : l1calogfex_bipb_tx_data_subtype;
    CIPB_TX_CTRL : l1calogfex_cipb_tx_ctrl_subtype;
    CIPB_TX_DATA : l1calogfex_cipb_tx_data_subtype;
    AIPB_RX_CTRL : l1calogfex_aipb_rx_ctrl_subtype;
    BIPB_RX_CTRL : l1calogfex_bipb_rx_ctrl_subtype;
    CIPB_RX_CTRL : l1calogfex_cipb_rx_ctrl_subtype;
    ZIPB_TX_CTRL : l1calogfex_zipb_tx_ctrl_subtype;
    ZIPB_TX_DATA : l1calogfex_zipb_tx_data_subtype;
    ZIPB_RX_CTRL : l1calogfex_zipb_rx_ctrl_subtype;
    AIPB_TX_STAT : l1calogfex_aipb_tx_stat_subtype;
    BIPB_TX_STAT : l1calogfex_bipb_tx_stat_subtype;
    CIPB_TX_STAT : l1calogfex_cipb_tx_stat_subtype;
    AIPB_RX_STAT : l1calogfex_aipb_rx_stat_subtype;
    AIPB_RX_DATA : l1calogfex_aipb_rx_data_subtype;
    BIPB_RX_STAT : l1calogfex_bipb_rx_stat_subtype;
    BIPB_RX_DATA : l1calogfex_bipb_rx_data_subtype;
    CIPB_RX_STAT : l1calogfex_cipb_rx_stat_subtype;
    CIPB_RX_DATA : l1calogfex_cipb_rx_data_subtype;
    ZIPB_TX_STAT : l1calogfex_zipb_tx_stat_subtype;
    ZIPB_RX_STAT : l1calogfex_zipb_rx_stat_subtype;
    ZIPB_RX_DATA : l1calogfex_zipb_rx_data_subtype;
    INIT_STAT : l1calogfex_init_stat_subtype;
    TEST : l1calogfex_status_test_record_type;
end record l1calogfex_status_record_type;
    

-- control hierarchy data types
    
type l1calogfex_control_n_bcrd_ctrl_record_type is record
    GLBL_LNKS : l1calogfex_n_bcrd_ctrl_glbl_lnks_subtype;
    JET_LNKS : l1calogfex_n_bcrd_ctrl_jet_lnks_subtype;
    TWR_LNKS : l1calogfex_n_bcrd_ctrl_twr_lnks_subtype;
end record l1calogfex_control_n_bcrd_ctrl_record_type;
    
type l1calogfex_control_gbt_ctrl_record_type is record
    SYNC : l1calogfex_gbt_ctrl_sync_subtype;
    RST : l1calogfex_gbt_ctrl_rst_subtype;
end record l1calogfex_control_gbt_ctrl_record_type;
    
type l1calogfex_control_ecr_ctrl_record_type is record
    VALUE : l1calogfex_ecr_ctrl_value_subtype;
    CLEAR : l1calogfex_ecr_ctrl_clear_subtype;
    UPDATE : l1calogfex_ecr_ctrl_update_subtype;
end record l1calogfex_control_ecr_ctrl_record_type;
    
type l1calogfex_control_test_record_type is record
    INIT_STAT_rw : l1calogfex_test_init_stat_rw_subtype;
end record l1calogfex_control_test_record_type;
    
type l1calogfex_control_record_type is record
    CTEST_REG : l1calogfex_ctest_reg_subtype;
    N_BCRD_CTRL : l1calogfex_control_n_bcrd_ctrl_record_type;
    GBT_CTRL : l1calogfex_control_gbt_ctrl_record_type;
    ECR_CTRL : l1calogfex_control_ecr_ctrl_record_type;
    AIPB_TX_CTRL : l1calogfex_aipb_tx_ctrl_subtype;
    AIPB_TX_DATA : l1calogfex_aipb_tx_data_subtype;
    BIPB_TX_CTRL : l1calogfex_bipb_tx_ctrl_subtype;
    BIPB_TX_DATA : l1calogfex_bipb_tx_data_subtype;
    CIPB_TX_CTRL : l1calogfex_cipb_tx_ctrl_subtype;
    CIPB_TX_DATA : l1calogfex_cipb_tx_data_subtype;
    AIPB_RX_CTRL : l1calogfex_aipb_rx_ctrl_subtype;
    BIPB_RX_CTRL : l1calogfex_bipb_rx_ctrl_subtype;
    CIPB_RX_CTRL : l1calogfex_cipb_rx_ctrl_subtype;
    ZIPB_TX_CTRL : l1calogfex_zipb_tx_ctrl_subtype;
    ZIPB_TX_DATA : l1calogfex_zipb_tx_data_subtype;
    ZIPB_RX_CTRL : l1calogfex_zipb_rx_ctrl_subtype;
    TEST : l1calogfex_control_test_record_type;
end record l1calogfex_control_record_type;
    


end package l1calogfex_pkg;
