-- Automatically generated by WhishList - https://github.com/mvsoliveira/wishlist/
-- Package name: l1calogfex_pkg
-- Description : IPbus address table for the L1Calo gFEX zynq FPGA

library ieee;
use ieee.std_logic_1164.all;

package l1calogfex_pkg is

-- register data types

subtype l1calogfex_ctest_reg_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_n_bcrd_ctrl_glbl_lnks_subtype is std_logic_vector(8 downto 0);
subtype l1calogfex_n_bcrd_ctrl_jet_lnks_subtype is std_logic_vector(8 downto 0);
subtype l1calogfex_n_bcrd_ctrl_twr_lnks_subtype is std_logic_vector(13 downto 0);
subtype l1calogfex_gbt_ctrl_sync_subtype is std_logic;
subtype l1calogfex_gbt_ctrl_rst_subtype is std_logic;
subtype l1calogfex_ecr_ctrl_value_subtype is std_logic_vector(7 downto 0);
subtype l1calogfex_ecr_ctrl_clear_subtype is std_logic;
subtype l1calogfex_ecr_ctrl_update_subtype is std_logic;
subtype l1calogfex_date_time_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_git_hash_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_fw_ver_code_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_aipb_tx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_aipb_tx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_bipb_tx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_bipb_tx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_cipb_tx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_cipb_tx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_aipb_rx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_bipb_rx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_cipb_rx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_zipb_tx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_zipb_tx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_zipb_rx_ctrl_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_aipb_tx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_bipb_tx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_cipb_tx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_aipb_rx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_aipb_rx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_bipb_rx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_bipb_rx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_cipb_rx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_cipb_rx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_zipb_tx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_zipb_rx_stat_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_zipb_rx_data_subtype is std_logic_vector(31 downto 0);
subtype l1calogfex_init_stat_subtype is std_logic_vector(31 downto 0);

-- status hierarchy data types
        
        
        
        
type l1calogfex_status_record_type is record
    date_time : l1calogfex_date_time_subtype;
    git_hash : l1calogfex_git_hash_subtype;
    fw_ver_code : l1calogfex_fw_ver_code_subtype;
    aipb_tx_stat : l1calogfex_aipb_tx_stat_subtype;
    bipb_tx_stat : l1calogfex_bipb_tx_stat_subtype;
    cipb_tx_stat : l1calogfex_cipb_tx_stat_subtype;
    aipb_rx_stat : l1calogfex_aipb_rx_stat_subtype;
    aipb_rx_data : l1calogfex_aipb_rx_data_subtype;
    bipb_rx_stat : l1calogfex_bipb_rx_stat_subtype;
    bipb_rx_data : l1calogfex_bipb_rx_data_subtype;
    cipb_rx_stat : l1calogfex_cipb_rx_stat_subtype;
    cipb_rx_data : l1calogfex_cipb_rx_data_subtype;
    zipb_tx_stat : l1calogfex_zipb_tx_stat_subtype;
    zipb_rx_stat : l1calogfex_zipb_rx_stat_subtype;
    zipb_rx_data : l1calogfex_zipb_rx_data_subtype;
    init_stat : l1calogfex_init_stat_subtype;
end record l1calogfex_status_record_type;

-- control hierarchy data types
        
type l1calogfex_control_n_bcrd_ctrl_record_type is record
    glbl_lnks : l1calogfex_n_bcrd_ctrl_glbl_lnks_subtype;
    jet_lnks : l1calogfex_n_bcrd_ctrl_jet_lnks_subtype;
    twr_lnks : l1calogfex_n_bcrd_ctrl_twr_lnks_subtype;
end record l1calogfex_control_n_bcrd_ctrl_record_type;
        
type l1calogfex_control_gbt_ctrl_record_type is record
    sync : l1calogfex_gbt_ctrl_sync_subtype;
    rst : l1calogfex_gbt_ctrl_rst_subtype;
end record l1calogfex_control_gbt_ctrl_record_type;
        
type l1calogfex_control_ecr_ctrl_record_type is record
    value : l1calogfex_ecr_ctrl_value_subtype;
    clear : l1calogfex_ecr_ctrl_clear_subtype;
    update : l1calogfex_ecr_ctrl_update_subtype;
end record l1calogfex_control_ecr_ctrl_record_type;
        
type l1calogfex_control_record_type is record
    ctest_reg : l1calogfex_ctest_reg_subtype;
    n_bcrd_ctrl : l1calogfex_control_n_bcrd_ctrl_record_type;
    gbt_ctrl : l1calogfex_control_gbt_ctrl_record_type;
    ecr_ctrl : l1calogfex_control_ecr_ctrl_record_type;
    aipb_tx_ctrl : l1calogfex_aipb_tx_ctrl_subtype;
    aipb_tx_data : l1calogfex_aipb_tx_data_subtype;
    bipb_tx_ctrl : l1calogfex_bipb_tx_ctrl_subtype;
    bipb_tx_data : l1calogfex_bipb_tx_data_subtype;
    cipb_tx_ctrl : l1calogfex_cipb_tx_ctrl_subtype;
    cipb_tx_data : l1calogfex_cipb_tx_data_subtype;
    aipb_rx_ctrl : l1calogfex_aipb_rx_ctrl_subtype;
    bipb_rx_ctrl : l1calogfex_bipb_rx_ctrl_subtype;
    cipb_rx_ctrl : l1calogfex_cipb_rx_ctrl_subtype;
    zipb_tx_ctrl : l1calogfex_zipb_tx_ctrl_subtype;
    zipb_tx_data : l1calogfex_zipb_tx_data_subtype;
    zipb_rx_ctrl : l1calogfex_zipb_rx_ctrl_subtype;
end record l1calogfex_control_record_type;


end package l1calogfex_pkg;
