"""
Wishbone-like simulation helpers for edawishlist.

Provides a cycle function factory that adapts to different DUT signal naming
conventions (e.g. foo_i/foo_o vs foo/foo_in/foo_out).
"""
import random
import logging
import cocotb
from bigtree import Node, preorder_iter
from cocotb._bridge import resume
from cocotb.clock import Clock
from cocotb.regression import TestFactory
from cocotb.triggers import RisingEdge, ReadOnly
from edawishlist.node import read_node, write_node, word_mask
from edawishlist.utils import get_logger, registers_to_node, node_to_register


def make_cycle(clk='clk_i', read='read_i', write='write_i',
               address='address_i', data_in='data_i', data_out='data_o'):
    """
    Return an async cycle(dut, address, mask, read_mode, write_values) function
    bound to the given DUT signal names.

    The address decoder is assumed to have a single registered pipeline stage:
    data_out is valid one rising edge after the strobe is asserted, matching
    the always_ff pattern generated by WhishList.

    Parameters
    ----------
    clk, read, write, address, data_in, data_out : str
        Attribute names on the DUT object for each bus signal.
    """
    async def cycle(dut, addresses, mask, read_mode, write_values):
        clk_sig    = getattr(dut, clk)
        read_sig   = getattr(dut, read)
        write_sig  = getattr(dut, write)
        addr_sig   = getattr(dut, address)
        din_sig    = getattr(dut, data_in)
        dout_sig   = getattr(dut, data_out)

        read_values = []
        # Zip address+[None] with [None]+mask so that each iteration sees the
        # address to drive *and* the mask to apply to the data captured in the
        # *previous* iteration (1-cycle registered output).
        for i, (addr, msk) in enumerate(zip(addresses + [None], [None] + mask)):
            await RisingEdge(clk_sig)
            if i < len(addresses):
                read_sig.value  = int(bool(read_mode))
                write_sig.value = int(not bool(read_mode))
                addr_sig.value  = addr
                if not read_mode:
                    din_sig.value = write_values[i]
            else:
                read_sig.value  = 0
                write_sig.value = 0
            if read_mode:
                await ReadOnly()
                if i > 0:
                    read_values.append(dout_sig.value.to_unsigned() & msk)
        if read_mode:
            return read_values
        return True

    return cycle


# Default cycle wired to WhishList's address-decoder port names (clk_i / *_i / *_o).
default_cycle = make_cycle()


class WishboneNode(Node):
    """
    Base node class for WhishList wishbone-like simulations.

    Subclass this per project, setting the class-level attributes:
        dut   – the cocotb DUT handle
        cycle – the cycle coroutine produced by make_cycle()

    Example
    -------
    class my_sim_node(WishboneNode):
        dut   = None   # set inside the test coroutine
        cycle = make_cycle(clk='clk', read='read', ...)
    """
    dut       = None
    cycle     = staticmethod(default_cycle)
    bus_width = 32

    def __init__(self, name, **kwargs):
        super().__init__(name, **kwargs)
        self.logger = get_logger(self.path_name, logging.INFO)

    @property
    def bus_mask(self):
        return word_mask(self.bus_width)

    def read_words(self):
        return resume(self.cycle)(
            self.dut, self.address, self.mask, read_mode=1, write_values=None
        )

    def write_words(self, data):
        return resume(self.cycle)(
            self.dut, self.address, self.mask, read_mode=0, write_values=data
        )

    def read(self):
        read_values = self.read_words()
        self.logger.debug(
            f'Reading {self.path_name} @ {[hex(a) for a in self.address]}'
            f' → {read_values}'
        )
        return registers_to_node(
            self.address, self.mask, read_values, self.bus_width, self.logger
        )

    def write(self, value):
        if self.permission != 'rw':
            self.logger.critical(
                f'Attempted write to read-only node {self.path_name}'
            )
            raise PermissionError(f'{self.path_name} is read-only')
        # Read-modify-write if any mask bit is 0
        if self.mask != [self.bus_mask] * len(self.mask):
            read_values = self.read_words()
        else:
            read_values = [0] * len(self.mask)
        write_values = node_to_register(
            value, self.address, self.mask, read_values, self.bus_width, self.logger
        )
        self.logger.debug(f'Writing {self.path_name} ← {write_values}')
        self.write_words(write_values)
        return True


async def wb_register_test(dut, logger, tree, clk_signal='clk_i',
                           read_signal='read_i', write_signal='write_i',
                           address_signal='address_i', data_in_signal='data_i',
                           data_out_signal='data_o',
                           clk_period_ns=10, shufle_order=True):
    """
    Generic register read/write stress test for a WhishList address decoder.

    Drives all rw leaves with random stimuli, drives all r leaves by setting
    the matching DUT status port, then reads back every leaf and asserts it
    matches the applied stimulus.
    """
    from operator import attrgetter

    cycle = make_cycle(clk_signal, read_signal, write_signal,
                       address_signal, data_in_signal, data_out_signal)

    cocotb.start_soon(Clock(getattr(dut, clk_signal), clk_period_ns,
                            units='ns').start(start_high=False))

    getattr(dut, read_signal).value  = 0
    getattr(dut, write_signal).value = 0
    getattr(dut, data_in_signal).value  = 0
    getattr(dut, address_signal).value  = 0

    bus_width = len(getattr(dut, data_in_signal))

    nodes = list(preorder_iter(tree, filter_condition=lambda n: n.is_leaf))

    # Apply stimuli
    if shufle_order:
        nodes = random.sample(nodes, len(nodes))
    for node in nodes:
        node.stimulus = random.randint(0, 2 ** node.width - 1)
        logger.info(f'Applying stimulus for {node.path_name}')
        if node.permission == 'r':
            path = node.path_name.lower().split('/')
            signal = attrgetter(f"{path[1]}_status_i.{'.'.join(path[2:])}")(dut)
            signal.value = node.stimulus
        else:
            await write_node(dut, node, node.stimulus, bus_width, logger, cycle)

    # Verify stimuli
    if shufle_order:
        nodes = random.sample(nodes, len(nodes))
    for node in nodes:
        logger.info(f'Verifying {node.path_name}')
        value = await read_node(dut, node, bus_width, logger, cycle)
        assert value == node.stimulus, (
            f'{node.path_name}: got 0x{value:x}, expected 0x{node.stimulus:x}')
